
# MAPEO ÉPICO GENERADO AUTOMÁTICAMENTE - 2025-07-03 20:12
# Total tickers: 647
# Cobertura: ÉPICA - Prácticamente todo el mercado USA

def get_epic_ticker_mapping():
    """Mapeo épico que cubre 647 tickers del mercado USA"""
    return {
    "AAPL": "Technology",
    "MSFT": "Technology",
    "GOOGL": "Media",
    "GOOG": "Media",
    "AMZN": "Retail",
    "META": "Media",
    "NVDA": "Technology",
    "TSLA": "Retail",
    "NFLX": "Media",
    "CRM": "Technology",
    "ORCL": "Technology",
    "ADBE": "Technology",
    "INTC": "Technology",
    "AMD": "Technology",
    "QCOM": "Technology",
    "AVGO": "Technology",
    "TXN": "Technology",
    "IBM": "Technology",
    "CSCO": "Technology",
    "NOW": "Technology",
    "SNOW": "Technology",
    "PLTR": "Technology",
    "COIN": "Banks",
    "RBLX": "Technology",
    "SHOP": "Technology",
    "SQ": "Technology",
    "BLOCK": "Technology",
    "ZM": "Technology",
    "DOCU": "Technology",
    "TEAM": "Technology",
    "OKTA": "Technology",
    "TWLO": "Technology",
    "UBER": "Industrial Goods",
    "LYFT": "Technology",
    "SNAP": "Technology",
    "PINS": "Technology",
    "SPOT": "Technology",
    "ZS": "Technology",
    "CRWD": "Technology",
    "NET": "Technology",
    "DDOG": "Technology",
    "MDB": "Technology",
    "FSLY": "Technology",
    "ROKU": "Technology",
    "SQM": "Technology",
    "AFRM": "Technology",
    "HOOD": "Technology",
    "PATH": "Technology",
    "JNJ": "Healthcare",
    "UNH": "Healthcare",
    "PFE": "Healthcare",
    "ABBV": "Healthcare",
    "TMO": "Healthcare",
    "ABT": "Healthcare",
    "DHR": "Healthcare",
    "BMY": "Healthcare",
    "LLY": "Healthcare",
    "MDT": "Healthcare",
    "GILD": "Healthcare",
    "AMGN": "Healthcare",
    "CVS": "Healthcare",
    "CI": "Healthcare",
    "HUM": "Healthcare",
    "ANTM": "Healthcare",
    "ELV": "Healthcare",
    "CNC": "Healthcare",
    "MOH": "Healthcare",
    "HCA": "Healthcare",
    "ISRG": "Healthcare",
    "SYK": "Healthcare",
    "EW": "Healthcare",
    "ZBH": "Healthcare",
    "MRNA": "Healthcare",
    "BNTX": "Healthcare",
    "VRTX": "Healthcare",
    "REGN": "Healthcare",
    "BIIB": "Healthcare",
    "ILMN": "Healthcare",
    "IQV": "Healthcare",
    "A": "Healthcare",
    "VAR": "Healthcare",
    "DXCM": "Healthcare",
    "VEEV": "Healthcare",
    "IDXX": "Healthcare",
    "MTD": "Healthcare",
    "IQVIA": "Healthcare",
    "BDX": "Healthcare",
    "BSX": "Healthcare",
    "JPM": "Banks",
    "BAC": "Banks",
    "WFC": "Banks",
    "C": "Banks",
    "GS": "Banks",
    "MS": "Banks",
    "USB": "Banks",
    "PNC": "Banks",
    "TFC": "Banks",
    "COF": "Banks",
    "BK": "Banks",
    "STT": "Banks",
    "SCHW": "Banks",
    "AXP": "Banks",
    "MA": "Banks",
    "V": "Banks",
    "PYPL": "Banks",
    "DFS": "Banks",
    "SYF": "Banks",
    "ALLY": "Banks",
    "FITB": "Banks",
    "HBAN": "Banks",
    "RF": "Banks",
    "KEY": "Banks",
    "CFG": "Banks",
    "BRK.A": "Banks",
    "BRK.B": "Banks",
    "PGR": "Banks",
    "TRV": "Banks",
    "ALL": "Banks",
    "AIG": "Banks",
    "MET": "Banks",
    "PRU": "Banks",
    "AFL": "Banks",
    "CB": "Banks",
    "SPGI": "Banks",
    "MCO": "Banks",
    "ICE": "Banks",
    "CME": "Banks",
    "NDAQ": "Banks",
    "WMT": "Food & Beverage",
    "HD": "Retail",
    "COST": "Food & Beverage",
    "LOW": "Retail",
    "TGT": "Food & Beverage",
    "TJX": "Retail",
    "SBUX": "Retail",
    "NKE": "Retail",
    "MCD": "Retail",
    "BKNG": "Retail",
    "EBAY": "Retail",
    "ETSY": "Retail",
    "W": "Retail",
    "RH": "Retail",
    "BBY": "Retail",
    "GPS": "Retail",
    "M": "Retail",
    "KSS": "Retail",
    "JWN": "Retail",
    "ROST": "Retail",
    "ULTA": "Retail",
    "DG": "Food & Beverage",
    "DLTR": "Food & Beverage",
    "FIVE": "Retail",
    "BIG": "Retail",
    "PEP": "Food & Beverage",
    "KO": "Food & Beverage",
    "PG": "Food & Beverage",
    "UL": "Food & Beverage",
    "MDLZ": "Food & Beverage",
    "GIS": "Food & Beverage",
    "K": "Food & Beverage",
    "CPB": "Food & Beverage",
    "CAG": "Food & Beverage",
    "TSN": "Food & Beverage",
    "KR": "Food & Beverage",
    "WBA": "Food & Beverage",
    "HSY": "Food & Beverage",
    "CLX": "Food & Beverage",
    "CL": "Food & Beverage",
    "KMB": "Food & Beverage",
    "CHD": "Food & Beverage",
    "SJM": "Food & Beverage",
    "XOM": "Oil & Gas",
    "CVX": "Oil & Gas",
    "COP": "Oil & Gas",
    "SLB": "Oil & Gas",
    "EOG": "Oil & Gas",
    "PSX": "Oil & Gas",
    "VLO": "Oil & Gas",
    "MPC": "Oil & Gas",
    "KMI": "Oil & Gas",
    "OKE": "Oil & Gas",
    "WMB": "Oil & Gas",
    "EPD": "Oil & Gas",
    "ET": "Oil & Gas",
    "MPLX": "Oil & Gas",
    "DVN": "Oil & Gas",
    "FANG": "Oil & Gas",
    "MRO": "Oil & Gas",
    "APA": "Oil & Gas",
    "HAL": "Oil & Gas",
    "BKR": "Oil & Gas",
    "OXY": "Oil & Gas",
    "PXD": "Oil & Gas",
    "CTRA": "Oil & Gas",
    "EQT": "Oil & Gas",
    "BA": "Industrial Goods",
    "CAT": "Industrial Goods",
    "DE": "Industrial Goods",
    "HON": "Industrial Goods",
    "GE": "Industrial Goods",
    "MMM": "Industrial Goods",
    "RTX": "Industrial Goods",
    "LMT": "Industrial Goods",
    "NOC": "Industrial Goods",
    "GD": "Industrial Goods",
    "UPS": "Industrial Goods",
    "FDX": "Industrial Goods",
    "LUV": "Industrial Goods",
    "DAL": "Industrial Goods",
    "UAL": "Industrial Goods",
    "AAL": "Industrial Goods",
    "JBLU": "Industrial Goods",
    "ALK": "Industrial Goods",
    "NEE": "Utilities",
    "DUK": "Utilities",
    "SO": "Utilities",
    "D": "Utilities",
    "EXC": "Utilities",
    "XEL": "Utilities",
    "SRE": "Utilities",
    "PEG": "Utilities",
    "AWK": "Utilities",
    "AEP": "Utilities",
    "ED": "Utilities",
    "ES": "Utilities",
    "PPL": "Utilities",
    "FE": "Utilities",
    "AES": "Utilities",
    "CNP": "Utilities",
    "AMT": "Real Estate",
    "CCI": "Real Estate",
    "EQIX": "Real Estate",
    "PLD": "Real Estate",
    "SPG": "Real Estate",
    "EXR": "Real Estate",
    "AVB": "Real Estate",
    "EQR": "Real Estate",
    "WELL": "Real Estate",
    "DLR": "Real Estate",
    "PSA": "Real Estate",
    "O": "Real Estate",
    "SBAC": "Real Estate",
    "VTR": "Real Estate",
    "ESS": "Real Estate",
    "MAA": "Real Estate",
    "UDR": "Real Estate",
    "CPT": "Real Estate",
    "HST": "Real Estate",
    "REG": "Real Estate",
    "LIN": "Basic Resources",
    "APD": "Basic Resources",
    "DD": "Basic Resources",
    "DOW": "Basic Resources",
    "ECL": "Basic Resources",
    "EMN": "Basic Resources",
    "LYB": "Basic Resources",
    "CF": "Basic Resources",
    "FMC": "Chemicals",
    "ALB": "Basic Resources",
    "CE": "Chemicals",
    "PPG": "Basic Resources",
    "SHW": "Basic Resources",
    "NUE": "Basic Resources",
    "STLD": "Basic Resources",
    "X": "Basic Resources",
    "CLF": "Basic Resources",
    "AA": "Basic Resources",
    "FCX": "Basic Resources",
    "NEM": "Basic Resources",
    "DIS": "Media",
    "CMCSA": "Media",
    "T": "Media",
    "VZ": "Media",
    "CHTR": "Media",
    "TMUS": "Media",
    "WBD": "Media",
    "PARA": "Media",
    "NWSA": "Media",
    "FOXA": "Media",
    "FOX": "Media",
    "DISH": "Media",
    "AOS": "Industrial Goods",
    "ACN": "Technology",
    "ABNB": "Retail",
    "AKAM": "Technology",
    "ARE": "Real Estate",
    "ALGN": "Healthcare",
    "ALLE": "Industrial Goods",
    "LNT": "Utilities",
    "MO": "Food & Beverage",
    "AMCR": "Basic Resources",
    "AEE": "Utilities",
    "AMP": "Banks",
    "AME": "Industrial Goods",
    "APH": "Technology",
    "ADI": "Technology",
    "ANSS": "Technology",
    "AON": "Banks",
    "APO": "Banks",
    "AMAT": "Technology",
    "APTV": "Retail",
    "ACGL": "Banks",
    "ADM": "Food & Beverage",
    "ANET": "Technology",
    "AJG": "Banks",
    "AIZ": "Banks",
    "ATO": "Utilities",
    "ADSK": "Technology",
    "ADP": "Industrial Goods",
    "AZO": "Retail",
    "AVY": "Basic Resources",
    "AXON": "Industrial Goods",
    "BALL": "Basic Resources",
    "BAX": "Healthcare",
    "BRK-B": "Banks",
    "TECH": "Healthcare",
    "BLK": "Banks",
    "BX": "Banks",
    "BR": "Industrial Goods",
    "BRO": "Banks",
    "BF-B": "Food & Beverage",
    "BLDR": "Industrial Goods",
    "BG": "Food & Beverage",
    "BXP": "Real Estate",
    "CHRW": "Industrial Goods",
    "CDNS": "Technology",
    "CZR": "Retail",
    "CAH": "Healthcare",
    "KMX": "Retail",
    "CCL": "Retail",
    "CARR": "Industrial Goods",
    "CBOE": "Banks",
    "CBRE": "Real Estate",
    "CDW": "Technology",
    "COR": "Healthcare",
    "CRL": "Healthcare",
    "CMG": "Retail",
    "CINF": "Banks",
    "CTAS": "Industrial Goods",
    "CMS": "Utilities",
    "CTSH": "Technology",
    "STZ": "Food & Beverage",
    "CEG": "Utilities",
    "COO": "Healthcare",
    "CPRT": "Industrial Goods",
    "GLW": "Technology",
    "CPAY": "Banks",
    "CTVA": "Basic Resources",
    "CSGP": "Real Estate",
    "CSX": "Industrial Goods",
    "CMI": "Industrial Goods",
    "DRI": "Retail",
    "DVA": "Healthcare",
    "DAY": "Industrial Goods",
    "DECK": "Retail",
    "DELL": "Technology",
    "DPZ": "Retail",
    "DASH": "Retail",
    "DOV": "Industrial Goods",
    "DHI": "Retail",
    "DTE": "Utilities",
    "ETN": "Industrial Goods",
    "EIX": "Utilities",
    "EA": "Media",
    "EMR": "Industrial Goods",
    "ENPH": "Technology",
    "ETR": "Utilities",
    "EPAM": "Technology",
    "EFX": "Industrial Goods",
    "ERIE": "Banks",
    "EL": "Food & Beverage",
    "EG": "Banks",
    "EVRG": "Utilities",
    "EXE": "Oil & Gas",
    "EXPE": "Retail",
    "EXPD": "Industrial Goods",
    "FFIV": "Technology",
    "FDS": "Banks",
    "FICO": "Technology",
    "FAST": "Industrial Goods",
    "FRT": "Real Estate",
    "FIS": "Banks",
    "FSLR": "Technology",
    "FI": "Banks",
    "F": "Retail",
    "FTNT": "Technology",
    "FTV": "Industrial Goods",
    "BEN": "Banks",
    "GRMN": "Retail",
    "IT": "Technology",
    "GEHC": "Healthcare",
    "GEV": "Industrial Goods",
    "GEN": "Technology",
    "GNRC": "Industrial Goods",
    "GM": "Retail",
    "GPC": "Retail",
    "GPN": "Banks",
    "GL": "Banks",
    "GDDY": "Technology",
    "HIG": "Banks",
    "HAS": "Retail",
    "DOC": "Real Estate",
    "HSIC": "Healthcare",
    "HES": "Oil & Gas",
    "HPE": "Technology",
    "HLT": "Retail",
    "HOLX": "Healthcare",
    "HRL": "Food & Beverage",
    "HWM": "Industrial Goods",
    "HPQ": "Technology",
    "HUBB": "Industrial Goods",
    "HII": "Industrial Goods",
    "IEX": "Industrial Goods",
    "ITW": "Industrial Goods",
    "INCY": "Healthcare",
    "IR": "Industrial Goods",
    "PODD": "Healthcare",
    "IFF": "Basic Resources",
    "IP": "Basic Resources",
    "IPG": "Media",
    "INTU": "Technology",
    "IVZ": "Banks",
    "INVH": "Real Estate",
    "IRM": "Real Estate",
    "JBHT": "Industrial Goods",
    "JBL": "Technology",
    "JKHY": "Banks",
    "J": "Industrial Goods",
    "JCI": "Industrial Goods",
    "KVUE": "Food & Beverage",
    "KDP": "Food & Beverage",
    "KEYS": "Technology",
    "KIM": "Real Estate",
    "KKR": "Banks",
    "KLAC": "Technology",
    "KHC": "Food & Beverage",
    "LHX": "Industrial Goods",
    "LH": "Healthcare",
    "LRCX": "Technology",
    "LW": "Food & Beverage",
    "LVS": "Retail",
    "LDOS": "Industrial Goods",
    "LEN": "Retail",
    "LII": "Industrial Goods",
    "LYV": "Media",
    "LKQ": "Retail",
    "L": "Banks",
    "LULU": "Retail",
    "MTB": "Banks",
    "MKTX": "Banks",
    "MAR": "Retail",
    "MMC": "Banks",
    "MLM": "Basic Resources",
    "MAS": "Industrial Goods",
    "MTCH": "Media",
    "MKC": "Food & Beverage",
    "MCK": "Healthcare",
    "MRK": "Healthcare",
    "MGM": "Retail",
    "MCHP": "Technology",
    "MU": "Technology",
    "MHK": "Retail",
    "TAP": "Food & Beverage",
    "MPWR": "Technology",
    "MNST": "Food & Beverage",
    "MOS": "Basic Resources",
    "MSI": "Technology",
    "MSCI": "Banks",
    "NTAP": "Technology",
    "NWS": "Media",
    "NI": "Utilities",
    "NDSN": "Industrial Goods",
    "NSC": "Industrial Goods",
    "NTRS": "Banks",
    "NCLH": "Retail",
    "NRG": "Utilities",
    "NVR": "Retail",
    "NXPI": "Technology",
    "ORLY": "Retail",
    "ODFL": "Industrial Goods",
    "OMC": "Media",
    "ON": "Technology",
    "OTIS": "Industrial Goods",
    "PCAR": "Industrial Goods",
    "PKG": "Basic Resources",
    "PANW": "Technology",
    "PH": "Industrial Goods",
    "PAYX": "Industrial Goods",
    "PAYC": "Industrial Goods",
    "PNR": "Industrial Goods",
    "PCG": "Utilities",
    "PM": "Food & Beverage",
    "PNW": "Utilities",
    "POOL": "Retail",
    "PFG": "Banks",
    "PTC": "Technology",
    "PHM": "Retail",
    "PWR": "Industrial Goods",
    "DGX": "Healthcare",
    "RL": "Retail",
    "RJF": "Banks",
    "RSG": "Industrial Goods",
    "RMD": "Healthcare",
    "RVTY": "Healthcare",
    "ROK": "Industrial Goods",
    "ROL": "Industrial Goods",
    "ROP": "Technology",
    "RCL": "Retail",
    "STX": "Technology",
    "SWKS": "Technology",
    "SW": "Basic Resources",
    "SNA": "Industrial Goods",
    "SOLV": "Healthcare",
    "SWK": "Industrial Goods",
    "STE": "Healthcare",
    "SMCI": "Technology",
    "SNPS": "Technology",
    "SYY": "Food & Beverage",
    "TROW": "Banks",
    "TTWO": "Media",
    "TPR": "Retail",
    "TRGP": "Oil & Gas",
    "TEL": "Technology",
    "TDY": "Technology",
    "TER": "Technology",
    "TPL": "Oil & Gas",
    "TXT": "Industrial Goods",
    "TKO": "Media",
    "TSCO": "Retail",
    "TT": "Industrial Goods",
    "TDG": "Industrial Goods",
    "TRMB": "Technology",
    "TYL": "Technology",
    "UNP": "Industrial Goods",
    "URI": "Industrial Goods",
    "UHS": "Healthcare",
    "VLTO": "Industrial Goods",
    "VRSN": "Technology",
    "VRSK": "Industrial Goods",
    "VTRS": "Healthcare",
    "VICI": "Real Estate",
    "VST": "Utilities",
    "VMC": "Basic Resources",
    "WRB": "Banks",
    "GWW": "Industrial Goods",
    "WAB": "Industrial Goods",
    "WM": "Industrial Goods",
    "WAT": "Healthcare",
    "WEC": "Utilities",
    "WST": "Healthcare",
    "WDC": "Technology",
    "WY": "Real Estate",
    "WSM": "Retail",
    "WTW": "Banks",
    "WDAY": "Technology",
    "WYNN": "Retail",
    "XYL": "Industrial Goods",
    "YUM": "Retail",
    "ZBRA": "Technology",
    "ZTS": "Healthcare",
    "APP": "Technology",
    "ARM": "Technology",
    "ASML": "Technology",
    "AZN": "Healthcare",
    "CCEP": "Food & Beverage",
    "GFS": "Technology",
    "MRVL": "Technology",
    "MELI": "Retail",
    "MSTR": "Technology",
    "PDD": "Retail",
    "TTD": "Media",
    "SMAR": "Technology",
    "QTWO": "Technology",
    "EVBG": "Technology",
    "FRSH": "Technology",
    "APPF": "Technology",
    "MITK": "Technology",
    "PSTG": "Technology",
    "COUP": "Technology",
    "ALRM": "Technology",
    "GTLB": "Technology",
    "PCTY": "Technology",
    "ASAN": "Technology",
    "GMED": "Healthcare",
    "MMSI": "Healthcare",
    "OMCL": "Healthcare",
    "KRYS": "Healthcare",
    "LMAT": "Healthcare",
    "NVST": "Healthcare",
    "TMDX": "Healthcare",
    "NEOG": "Healthcare",
    "ATRC": "Healthcare",
    "IRTC": "Healthcare",
    "GKOS": "Healthcare",
    "VBTX": "Banks",
    "TOWN": "Banks",
    "BANF": "Banks",
    "CASH": "Banks",
    "GSBC": "Banks",
    "HOMB": "Banks",
    "UMBF": "Banks",
    "CBSH": "Banks",
    "FFIN": "Banks",
    "BOKF": "Banks",
    "ONB": "Banks",
    "TCBI": "Banks",
    "ASTE": "Industrial Goods",
    "ROAD": "Industrial Goods",
    "PATK": "Industrial Goods",
    "MATW": "Industrial Goods",
    "WERN": "Industrial Goods",
    "SAIA": "Industrial Goods",
    "KNX": "Industrial Goods",
    "ARCB": "Industrial Goods",
    "PLAY": "Retail",
    "TXRH": "Retail",
    "WING": "Retail",
    "CAKE": "Retail",
    "BLMN": "Retail",
    "RRGB": "Retail",
    "EAT": "Retail",
    "PZZA": "Retail",
    "SM": "Oil & Gas",
    "CDEV": "Oil & Gas",
    "MTDR": "Oil & Gas",
    "AROC": "Oil & Gas",
    "GPOR": "Oil & Gas",
    "CRGY": "Oil & Gas",
    "MGEE": "Oil & Gas",
    "XLK": "Technology",
    "VGT": "Technology",
    "XLV": "Healthcare",
    "VHT": "Healthcare",
    "XLF": "Banks",
    "VFH": "Banks",
    "XLE": "Oil & Gas",
    "VDE": "Oil & Gas",
    "XLI": "Industrial Goods",
    "VIS": "Industrial Goods",
    "XLY": "Retail",
    "XLP": "Food & Beverage",
    "XLU": "Utilities",
    "VPU": "Utilities",
    "XLRE": "Real Estate",
    "VNQ": "Real Estate",
    "XLB": "Basic Resources",
    "VAW": "Basic Resources"
}

# Para actualizar tu Enhanced Analyzer, reemplaza self.comprehensive_ticker_mapping con:
# self.comprehensive_ticker_mapping = get_epic_ticker_mapping()
