/**
 * Ticker → domain map for Clearbit logo API.
 * Clearbit URL: https://logo.clearbit.com/{domain}?size=64
 *
 * Coverage: ~200 US + EU blue-chips that commonly appear in VALUE/GARP screens.
 */
const TICKER_DOMAIN: Record<string, string> = {
  // ── US Tech ──────────────────────────────────────────────
  AAPL:  'apple.com',
  MSFT:  'microsoft.com',
  GOOGL: 'google.com',
  GOOG:  'google.com',
  AMZN:  'amazon.com',
  META:  'meta.com',
  NVDA:  'nvidia.com',
  TSLA:  'tesla.com',
  AMD:   'amd.com',
  INTC:  'intel.com',
  QCOM:  'qualcomm.com',
  AVGO:  'broadcom.com',
  ORCL:  'oracle.com',
  CRM:   'salesforce.com',
  ADBE:  'adobe.com',
  NOW:   'servicenow.com',
  PANW:  'paloaltonetworks.com',
  SNOW:  'snowflake.com',
  PLTR:  'palantir.com',
  IBM:   'ibm.com',
  CSCO:  'cisco.com',
  TXN:   'ti.com',
  MU:    'micron.com',
  AMAT:  'appliedmaterials.com',
  LRCX:  'lamresearch.com',
  KLAC:  'kla.com',
  HPQ:   'hp.com',
  DELL:  'dell.com',
  NET:   'cloudflare.com',
  DDOG:  'datadoghq.com',
  ZS:    'zscaler.com',
  TTD:   'thetradedesk.com',
  RBLX:  'roblox.com',

  // ── US Financials ─────────────────────────────────────────
  JPM:     'jpmorganchase.com',
  BAC:     'bankofamerica.com',
  GS:      'goldmansachs.com',
  MS:      'morganstanley.com',
  WFC:     'wellsfargo.com',
  C:       'citi.com',
  BLK:     'blackrock.com',
  V:       'visa.com',
  MA:      'mastercard.com',
  AXP:     'americanexpress.com',
  'BRK.B': 'berkshirehathaway.com',
  'BRK.A': 'berkshirehathaway.com',
  BRK:     'berkshirehathaway.com',
  SPGI:    'spglobal.com',
  MCO:     'moodys.com',
  ICE:     'intercontinentalexchange.com',
  CME:     'cmegroup.com',
  USB:     'usbank.com',
  PNC:     'pnc.com',
  COF:     'capitalone.com',
  AIG:     'aig.com',
  PRU:     'prudential.com',
  MET:     'metlife.com',
  AFL:     'aflac.com',
  ALL:     'allstate.com',
  TRV:     'travelers.com',
  CB:      'chubb.com',
  MMC:     'marsh.com',
  AON:     'aon.com',

  // ── US Healthcare ─────────────────────────────────────────
  JNJ:  'jnj.com',
  PFE:  'pfizer.com',
  MRK:  'merck.com',
  ABBV: 'abbvie.com',
  LLY:  'lilly.com',
  BMY:  'bms.com',
  UNH:  'unitedhealthgroup.com',
  CVS:  'cvs.com',
  MDT:  'medtronic.com',
  ABT:  'abbott.com',
  TMO:  'thermofisher.com',
  DHR:  'danaher.com',
  SYK:  'stryker.com',
  BSX:  'bostonscientific.com',
  EW:   'edwards.com',
  ISRG: 'intuitivesurgical.com',
  ZBH:  'zimmerbiomet.com',
  BDX:  'bd.com',
  CI:   'cigna.com',
  HUM:  'humana.com',
  CNC:  'centene.com',
  AMGN: 'amgen.com',
  GILD: 'gilead.com',
  BIIB: 'biogen.com',
  REGN: 'regeneron.com',
  VRTX: 'vrtx.com',
  IQV:  'iqvia.com',
  MRNA: 'modernatx.com',

  // ── US Consumer Discretionary ─────────────────────────────
  WMT:  'walmart.com',
  COST: 'costco.com',
  HD:   'homedepot.com',
  LOW:  'lowes.com',
  TGT:  'target.com',
  AMZN_CONSUMER: 'amazon.com',
  MCD:  'mcdonalds.com',
  SBUX: 'starbucks.com',
  NKE:  'nike.com',
  TJX:  'tjx.com',
  BKNG: 'booking.com',
  MAR:  'marriott.com',
  HLT:  'hilton.com',
  MGM:  'mgmresorts.com',
  F:    'ford.com',
  GM:   'gm.com',

  // ── US Consumer Staples ───────────────────────────────────
  PM:   'pmi.com',
  MO:   'altria.com',
  KO:   'coca-cola.com',
  PEP:  'pepsico.com',
  PG:   'pg.com',
  CL:   'colgatepalmolive.com',
  KHC:  'kraftheinzcompany.com',
  GIS:  'generalmills.com',
  K:    'kelloggs.com',
  CAG:  'conagra.com',
  MKC:  'mccormick.com',
  SJM:  'jmsmucker.com',

  // ── US Energy ─────────────────────────────────────────────
  XOM:  'exxonmobil.com',
  CVX:  'chevron.com',
  COP:  'conocophillips.com',
  SLB:  'slb.com',
  EOG:  'eogresources.com',
  PXD:  'pioneernaturalresources.com',
  MPC:  'marathonpetroleum.com',
  PSX:  'phillips66.com',
  VLO:  'valero.com',
  DVN:  'devonenergy.com',
  HAL:  'halliburton.com',

  // ── US Industrials ────────────────────────────────────────
  CAT:  'caterpillar.com',
  DE:   'deere.com',
  GE:   'ge.com',
  HON:  'honeywell.com',
  MMM:  '3m.com',
  RTX:  'rtx.com',
  LMT:  'lockheedmartin.com',
  BA:   'boeing.com',
  UPS:  'ups.com',
  FDX:  'fedex.com',
  GD:   'gd.com',
  NOC:  'northropgrumman.com',
  EMR:  'emerson.com',
  ETN:  'eaton.com',
  PH:   'parker.com',
  ROK:  'rockwellautomation.com',
  XYL:  'xylem.com',
  IR:   'irco.com',
  PCAR: 'paccar.com',
  CTAS: 'cintas.com',
  RSG:  'republicservices.com',
  WM:   'wm.com',

  // ── US Telecom / Media ────────────────────────────────────
  T:    'att.com',
  VZ:   'verizon.com',
  TMUS: 't-mobile.com',
  NFLX: 'netflix.com',
  DIS:  'thewaltdisneycompany.com',
  CMCSA:'comcast.com',
  WBD:  'wbd.com',
  PARA: 'paramount.com',
  FOX:  'fox.com',
  FOXA: 'fox.com',

  // ── US REITs & Utilities ──────────────────────────────────
  NEE:  'nexteraenergy.com',
  D:    'dominionenergy.com',
  DUK:  'duke-energy.com',
  SO:   'southerncompany.com',
  AEP:  'aep.com',
  EXC:  'exeloncorp.com',
  SRE:  'sempra.com',
  AMT:  'americantower.com',
  PLD:  'prologis.com',
  SPG:  'simon.com',
  O:    'realtyincome.com',
  WELL: 'welltower.com',
  EQIX: 'equinix.com',

  // ── EU — UK ───────────────────────────────────────────────
  'SHEL.L':  'shell.com',
  'BP.L':    'bp.com',
  'HSBA.L':  'hsbc.com',
  'BARC.L':  'barclays.com',
  'LLOY.L':  'lloydsbankinggroup.com',
  'RBS.L':   'natwest.com',
  'NWG.L':   'natwest.com',
  'AZN.L':   'astrazeneca.com',
  'GSK.L':   'gsk.com',
  'ULVR.L':  'unilever.com',
  'DGE.L':   'diageo.com',
  'RIO.L':   'riotinto.com',
  'AAL.L':   'angloamerican.com',
  'GLEN.L':  'glencore.com',
  'BHP.L':   'bhp.com',
  'VOD.L':   'vodafone.com',
  'BT-A.L':  'bt.com',
  'TSCO.L':  'tescoplc.com',
  'MKS.L':   'marksandspencer.com',
  'PRU.L':   'prudential.com',
  'LSEG.L':  'lseg.com',
  'NG.L':    'nationalgrid.com',

  // ── EU — Germany ─────────────────────────────────────────
  'BMW.DE':  'bmw.com',
  'VOW3.DE': 'volkswagen.com',
  'MBG.DE':  'mercedes-benz.com',
  'BAS.DE':  'basf.com',
  'BAYN.DE': 'bayer.com',
  'SIE.DE':  'siemens.com',
  'SAP.DE':  'sap.com',
  'DTE.DE':  'telekom.de',
  'DBK.DE':  'db.com',
  'ALV.DE':  'allianz.com',
  'MUV2.DE': 'munichre.com',
  'HEI.DE':  'heidelbergmaterials.com',
  'RWE.DE':  'rwe.com',
  'E.ON.DE': 'eon.com',
  'ADS.DE':  'adidas.com',

  // ── EU — France ───────────────────────────────────────────
  'MC.PA':   'lvmh.com',
  'TTE.PA':  'totalenergies.com',
  'SAN.PA':  'sanofi.com',
  'AI.PA':   'airliquide.com',
  'BNP.PA':  'bnpparibas.com',
  'GLE.PA':  'societegenerale.com',
  'ACA.PA':  'credit-agricole.com',
  'AIR.PA':  'airbus.com',
  'OR.PA':   'loreal.com',
  'KER.PA':  'kering.com',
  'HO.PA':   'thalesgroup.com',
  'SGO.PA':  'saint-gobain.com',
  'VIE.PA':  'veolia.com',
  'RMS.PA':  'hermes.com',

  // ── EU — Netherlands ──────────────────────────────────────
  'ASML.AS': 'asml.com',
  'INGA.AS': 'ing.com',
  'PHIA.AS': 'philips.com',
  'RDSA.AS': 'shell.com',
  'UNA.AS':  'unilever.com',
  'HEIA.AS': 'theheinekencompany.com',

  // ── EU — Spain ────────────────────────────────────────────
  'SAN.MC':  'santander.com',
  'BBVA.MC': 'bbva.com',
  'IBE.MC':  'iberdrola.com',
  'REP.MC':  'repsol.com',
  'ITX.MC':  'inditex.com',
  'TEF.MC':  'telefonica.com',
  'ACS.MC':  'grupoacs.com',
  'AMS.MC':  'amadeus.com',

  // ── EU — Switzerland ──────────────────────────────────────
  'NESN.SW': 'nestle.com',
  'NOVN.SW': 'novartis.com',
  'ROG.SW':  'roche.com',
  'ABBN.SW': 'abb.com',
  'ZURN.SW': 'zurich.com',
  'LONN.SW': 'lonza.com',
  'GIVN.SW': 'givaudan.com',
  'SIKA.SW': 'sika.com',
  'SREN.SW': 'swissre.com',
  'ALC.SW':  'alcon.com',
  'SCMN.SW': 'swisscom.ch',

  // ── EU — Denmark / Scandinavia ────────────────────────────
  'NOVO-B.CO': 'novonordisk.com',
  'ORSTED.CO': 'orsted.com',
  'NZYM-B.CO': 'novozymes.com',
  'MAERSK-B.CO': 'maersk.com',
  'VOLV-B.ST': 'volvo.com',
  'ERIC-B.ST': 'ericsson.com',
  'ATCO-A.ST': 'atlascopco.com',
  'SEB-A.ST':  'sebgroup.com',

  // ── EU — Italy ────────────────────────────────────────────
  'ENI.MI':   'eni.com',
  'ENEL.MI':  'enel.com',
  'ISP.MI':   'intesasanpaolo.com',
  'UCG.MI':   'unicreditgroup.eu',
  'STM.MI':   'st.com',
  'LUX.MI':   'luxottica.com',
  'REC.MI':   'recordati.it',

  // ── Standalone (no exchange suffix used in app) ───────────
  SAP:  'sap.com',
  ASML: 'asml.com',
  SHEL: 'shell.com',
  BP:   'bp.com',
  HSBA: 'hsbc.com',
  BARC: 'barclays.com',
  LLOY: 'lloydsbankinggroup.com',
  AZN:  'astrazeneca.com',
  GSK:  'gsk.com',
  ULVR: 'unilever.com',
  DGE:  'diageo.com',
  VOD:  'vodafone.com',
  NOVOB:'novonordisk.com',
  OR:   'loreal.com',
}

/**
 * Returns a logo URL for a given ticker.
 * Primary: Parqet CDN (accepts ticker symbols directly, free, ~3000 stocks)
 * Fallback handled in TickerLogo component via onError → initials badge.
 */
export function getLogoUrl(ticker: string): string {
  return `https://assets.parqet.com/logos/symbol/${encodeURIComponent(ticker)}?format=jpg`
}

/**
 * Clearbit fallback URL (for tickers not found on Parqet that are in our domain map).
 */
export function getClearbitUrl(ticker: string): string | null {
  const exact = TICKER_DOMAIN[ticker]
  if (exact) return `https://logo.clearbit.com/${exact}?size=64`
  const stripped = ticker.replace(/\.[A-Z]{1,3}$/, '')
  const base = TICKER_DOMAIN[stripped] ?? TICKER_DOMAIN[stripped.replaceAll('-', '')]
  return base ? `https://logo.clearbit.com/${base}?size=64` : null
}
